accessible_schedule:
  description: 'Allow all employees read-only access to approved and scheduled jobs'
  type: 'boolean'
  default: false
job_notifications:
  description: 'Send email notifications when a job starts or completes'
  type: 'boolean'
  default: false
outgoing_email:
  description: 'Enable outgoing email functionality'
  type: 'boolean'
  default: false
job_email_alternate_send:
  description: 'Use new sending methods for job emails'
  type: 'boolean'
  default: false
receipt_alternate_send:
  description: 'Use new sending methods for receipt emails'
  type: 'boolean'
  default: false
quote_alternate_send:
  description: 'Use new sending methods for quote emails'
  type: 'boolean'
  default: false